name: Recipe App Sandbox Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      BASE-IMAGE: oladipupo206/recipe-app
      RELEASE-TAG: v1.0.0    